server:
  port: ${port:8081}
  servlet:
    contextPath: /api

spring:
  datasource:
    url: jdbc:mysql://database:3306/goecommerce?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false